name: box

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # point_cloud:
    #   shape: [4096, 3]
    #   type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dim
    gridmap:
      shape: [40, 40, 40]
      type: gridmap
  action:
    shape: [7]


dataset:
  _target_: diffusion_policy_3d.dataset.gridmap_dataset.GridmapDataset
  zarr_path: data/box_zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 90

  use_img: false
  use_depth: false
  use_gridmap: true

  # num_points: ${policy.pointcloud_encoder_cfg.num_points}
